export default {
    GET_PRODUCTS_ACTION: 'GET_PRODUCTS_ACTION',
    GET_PRODUCTS_REQUEST: 'GET_PRODUCTS_REQUEST',
    GET_PRODUCTS_RESPONSE: 'GET_PRODUCTS_RESPONSE',
    GET_PRODUCTS_ERROR: 'GET_PRODUCTS_ERROR',

    PUSH_PRODUCT_ACTION: 'PUSH_PRODUCT_ACTION',
    PUSH_PRODUCT_REQUEST: 'PUSH_PRODUCT_REQUEST',
    PUSH_PRODUCT_RESPONSE: 'PUSH_PRODUCT_RESPONSE',
    PUSH_PRODUCT_ERROR: 'PUSH_PRODUCT_ERROR',

    POP_PRODUCT_ACTION: 'POP_PRODUCT_ACTION',
    POP_PRODUCT_REQUEST: 'POP_PRODUCT_REQUEST',
    POP_PRODUCT_RESPONSE: 'POP_PRODUCT_RESPONSE',
    POP_PRODUCT_ERROR: 'POP_PRODUCT_ERROR',

    REMOVE_PRODUCT_ACTION: 'REMOVE_PRODUCT_ACTION',
    REMOVE_PRODUCT_REQUEST: 'REMOVE_PRODUCT_REQUEST',
    REMOVE_PRODUCT_RESPONSE: 'REMOVE_PRODUCT_RESPONSE',
    REMOVE_PRODUCT_ERROR: 'REMOVE_PRODUCT_ERROR',
}

